client.ops.grid: Handle expired cache
If the cache has expired, then we can wind up with the situation where
`op` is `None`, so the `if` block falls through to the `else` branch
erroniously.

This causes a stack trace like the following:

```
    2017-02-17 01:49:00,039 pyhaystack.client.WideskyHaystackSession.his_write_frame[his.py: 726] WARNING Unable to probe multi-his-write support
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pyhaystack/client/ops/his.py", line 723, in _on_probe_multi
        result = operation.result
      File "/usr/lib/python2.7/dist-packages/pyhaystack/util/state.py", line 97, in result
        self._result.reraise()
      File "/usr/lib/python2.7/dist-packages/pyhaystack/util/asyncexc.py", line 28, in reraise
        reraise(*self._exc_info)
      File "/usr/lib/python2.7/dist-packages/pyhaystack/client/ops/feature.py", line 93, in _on_got_about
        self._about = operation.result
      File "/usr/lib/python2.7/dist-packages/pyhaystack/util/state.py", line 97, in result
        self._result.reraise()
      File "/usr/lib/python2.7/dist-packages/pyhaystack/util/asyncexc.py", line 28, in reraise
        reraise(*self._exc_info)
      File "/usr/lib/python2.7/dist-packages/pyhaystack/client/ops/grid.py", line 118, in _check_auth
        self._state_machine.auth_ok()
      File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 297, in fn
        self.transition()
      File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 290, in _tran
        self._enter_state(e)
      File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 341, in _enter_state
        return getattr(self, fnname)(e)
      File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 88, in _callback
        return func(obj, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/pyhaystack/client/ops/grid.py", line 177, in _do_check_cache
        op.done_sig.connect(_proxy)
    AttributeError: 'NoneType' object has no attribute 'done_sig'
```

We need to instead do our check while we have the mutex locked and
disregard the expired cache.